os: osx
language: node_js
node_js:
  - 12.5
if: branch = master AND commit_message =~ /^Release/
install: yarn install
script: 
  - yarn electron:generate-icons
  - yarn electron:build -mlw
deploy:
    provider: releases
    skip_cleanup: true
    token: $RELEASES_TOKEN
    file:
        - dist_electron/*.zip
        - dist_electron/*.exe
        - dist_electron/*.AppImage
        - dist_electron/*.dmg
    file_glob: true
    prerelease: true
    overwrite: true
    draft: true